backend: 
  name: github
  repo: a-trost/atrostdotcom

media_folder: static/assets

collections: 
  - name: post
    label: Posts
    folder: src/posts
    create: true
    fields: 
      - {name: title, label: Title}
      - {name: date, label: Create At, widget: date }
      - {name: body, label: Post, widget: markdown}